repos:
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: env PYTHONPATH="." pytest test/
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        always_run: true
        pass_filenames: false